### ISSUE TITLE
Outlined text in 01 Motivation renders incorrectly (Safari only, Chrome is ok)

### ISSUE THREAD

**Issue by raymundjacobs** [sunsten/landingpage#3]
<img width="1107" alt="Screenshot 2019-05-09 at 11 28 42" src="https://user-images.githubusercontent.com/30527251/57443133-b36faf00-724d-11e9-8a4e-8448a2ec445f.png">

**Comment by secretlifeof** [comment]
Fixed this. The text was font-weight bold.
